# Event name
name: on_push
# When the event should run
on:
  push:
    branches:
      - "**"  #This will run on all branches, and must be quoted to be handled by yaml
# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        node-version: [ '16.x' ]
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Install Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install latest stable chrome version 119.x 
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Run clean build with maven
        run: mvn clean compile
      #set start time
      - name: Set test run start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - name: Run tests with maven
        run: mvn clean test
      #set end time
      - name: Calculate test results data
        working-directory: src/test/resources
        if: always()
        run: |
          echo "TOTAL_TEST_DURATION=$(expr $(date +%s)  - ${START_TIME})s"
          ./test_results_script.sh
          
