# Event name
name: on_push
# When the event should run
on:
  push:
    branches:
      - "**"  #This will run on all branches, and must be quoted to be handled by yaml
# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v2
       #install Java
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      # Run: mvn test
      - name: Run tests with maven
        working-directory: CucumberPagObjects
        run: mvn clean test
# What steps within each job
