# Event name
name: on_push
# When the event should run
on:
  push:
    branches:
      - "**"  #This will run on all branches, and must be quoted to be handled by yaml
  schedule:
    - cron: '0 1 * * *' #This will run every day 1 AM. Calculated with https://crontab.guru/#0_1_*_*_*
# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      BUILDEVENT_FILE: './buildevents.txt'  #This is the root of out repository

    steps:
      - name: Get Build event data
        uses: kvrhdn/gha-buildevents@v1
        with:
          apiKey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: CucumberPagObjects-build-pipeline
          job-status: ${{ job.status }}
      #set start time
      - name: Set build and test run start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Install latest stable chrome version 119.x
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Run clean build with maven
        run: mvn compile
      #introduce start of span
      - name: Telemetry start - Maven tests
        if: always()
        run: |
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
          echo "STEP_ID='run-maven-tests'" >> $GITHUB_ENV
      - name: Run tests with maven
        run: mvn test
      #Finalize span
      - name: Telemetry - Collect build and test results data
        working-directory: src/test/resources
        env:
          PUSHGATEWAY_URL: ${{ secrets.PUSHGATEWAY_URL }}
          BUILDEVENT_FILE: ../../../${{ env.BUILDEVENT_FILE}}
        if: always()
        run: |
          echo "TOTAL_TEST_DURATION=$(expr $(date +%s)  - ${START_TIME})"
          echo "github_actions_total_test_duration $(expr $(date +%s) - ${START_TIME})" | curl --data-binary @- ${{ secrets.PUSHGATEWAY_URL }}/metrics/job/github_actions
          ./test_results_script.sh
          buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
